image: gcc:latest

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - apt update
          - apt install cmake ninja-build -y
          - git submodule update --init
          - mkdir build
          - cd build
          - cmake -DTARGET_64BIT_SUPPORT=ON ..
          - ninja se-scope-test
          - export GTEST_OUTPUT="xml:test-results/test-results.xml"
          - ./test/se-scope-test