image: gcc:latest

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - apt update
          - apt install cmake ninja-build -y
          - sed -i 's/url = \.\.\(.*\)/url = git@bitbucket.org:<your org>\1\.git/g' .gitmodules # See: https://stackoverflow.com/questions/70301880/bitbucket-pipeline-does-not-handle-relative-git-submodule-url-for-ssh-checkout
          - git submodule update --init
          - mkdir build
          - cd build
          - cmake -DTARGET_64BIT_SUPPORT=ON -GNinja ..
          - ninja se-scope-test
          - export GTEST_OUTPUT="xml:test-results/test-results.xml"
          - ./test/se-scope-test
