image: gcc:latest

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - apt update
          - apt install cmake -y
          - git submodule update --init
          - mkdir build
          - cd build
          - cmake ..
          - make se-scope-test
          - ctest -R se-scope-test --no-compress-output --output-on-failure -VV -T Test
          - mv Testing test-results