# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: se-scope.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='se-scope.proto',
  package='SC',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0ese-scope.proto\x12\x02SC\"M\n\x07Trigger\x12\r\n\x05\x63l_id\x18\x01 \x01(\r\x12\x13\n\x0b\x63l_data_ind\x18\x02 \x01(\r\x12\x1e\n\x04mode\x18\x03 \x01(\x0e\x32\x10.SC.Trigger_Mode\"#\n\x07\x43hannel\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02\x12\n\n\x02id\x18\x02 \x01(\r\"f\n\x04\x44\x61ta\x12\x1d\n\x08\x63hannels\x18\x01 \x03(\x0b\x32\x0b.SC.Channel\x12\x12\n\ntimestamps\x18\x02 \x03(\x07\x12\r\n\x05t_inc\x18\x03 \x01(\r\x12\x1c\n\x07trigger\x18\x04 \x01(\x0b\x32\x0b.SC.Trigger*D\n\x08Var_Type\x12\x0c\n\x08SE_UINT8\x10\x00\x12\r\n\tSE_UINT16\x10\x01\x12\r\n\tSE_UINT32\x10\x02\x12\x0c\n\x08SE_FLOAT\x10\x03*8\n\x0cTrigger_Mode\x12\n\n\x06NORMAL\x10\x00\x12\x0e\n\nCONTINUOUS\x10\x01\x12\x0c\n\x08ONE_SHOT\x10\x02\x62\x06proto3')
)

_VAR_TYPE = _descriptor.EnumDescriptor(
  name='Var_Type',
  full_name='SC.Var_Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SE_UINT8', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SE_UINT16', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SE_UINT32', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SE_FLOAT', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=242,
  serialized_end=310,
)
_sym_db.RegisterEnumDescriptor(_VAR_TYPE)

Var_Type = enum_type_wrapper.EnumTypeWrapper(_VAR_TYPE)
_TRIGGER_MODE = _descriptor.EnumDescriptor(
  name='Trigger_Mode',
  full_name='SC.Trigger_Mode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NORMAL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONTINUOUS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ONE_SHOT', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=312,
  serialized_end=368,
)
_sym_db.RegisterEnumDescriptor(_TRIGGER_MODE)

Trigger_Mode = enum_type_wrapper.EnumTypeWrapper(_TRIGGER_MODE)
SE_UINT8 = 0
SE_UINT16 = 1
SE_UINT32 = 2
SE_FLOAT = 3
NORMAL = 0
CONTINUOUS = 1
ONE_SHOT = 2



_TRIGGER = _descriptor.Descriptor(
  name='Trigger',
  full_name='SC.Trigger',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cl_id', full_name='SC.Trigger.cl_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cl_data_ind', full_name='SC.Trigger.cl_data_ind', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mode', full_name='SC.Trigger.mode', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=99,
)


_CHANNEL = _descriptor.Descriptor(
  name='Channel',
  full_name='SC.Channel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='SC.Channel.data', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='SC.Channel.id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=136,
)


_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='SC.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channels', full_name='SC.Data.channels', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamps', full_name='SC.Data.timestamps', index=1,
      number=2, type=7, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='t_inc', full_name='SC.Data.t_inc', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trigger', full_name='SC.Data.trigger', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=240,
)

_TRIGGER.fields_by_name['mode'].enum_type = _TRIGGER_MODE
_DATA.fields_by_name['channels'].message_type = _CHANNEL
_DATA.fields_by_name['trigger'].message_type = _TRIGGER
DESCRIPTOR.message_types_by_name['Trigger'] = _TRIGGER
DESCRIPTOR.message_types_by_name['Channel'] = _CHANNEL
DESCRIPTOR.message_types_by_name['Data'] = _DATA
DESCRIPTOR.enum_types_by_name['Var_Type'] = _VAR_TYPE
DESCRIPTOR.enum_types_by_name['Trigger_Mode'] = _TRIGGER_MODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Trigger = _reflection.GeneratedProtocolMessageType('Trigger', (_message.Message,), dict(
  DESCRIPTOR = _TRIGGER,
  __module__ = 'se_scope_pb2'
  # @@protoc_insertion_point(class_scope:SC.Trigger)
  ))
_sym_db.RegisterMessage(Trigger)

Channel = _reflection.GeneratedProtocolMessageType('Channel', (_message.Message,), dict(
  DESCRIPTOR = _CHANNEL,
  __module__ = 'se_scope_pb2'
  # @@protoc_insertion_point(class_scope:SC.Channel)
  ))
_sym_db.RegisterMessage(Channel)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), dict(
  DESCRIPTOR = _DATA,
  __module__ = 'se_scope_pb2'
  # @@protoc_insertion_point(class_scope:SC.Data)
  ))
_sym_db.RegisterMessage(Data)


# @@protoc_insertion_point(module_scope)
