/*!*****************************************************************************
 * @file         ScopeThreadRunner.h
 *
 * @copyright    Copyright (c) 2018 by Sourceengineers. All Rights Reserved.
 *
 * @authors      Samuel Schuepbach samuel.schuepbach@sourceengineers.com
 *
 * @brief        Run the runnables in ScopeObject
 *
 ******************************************************************************/

#ifndef SCOPETHREADRUNNER_H
#define SCOPETHREADRUNNER_H

#include <Scope/GeneralPurpose/IMutex.h>
#include <Scope/Builders/ScopeBuilder.h>

/******************************************************************************
 Public functions
******************************************************************************/
/**
 * Runs the scope in a thread context
 * @param scope Object filled with runnables, generated by the ScopeBuilder
 */
void ScopeThreadRunner_runScope(ScopeObject scope);

/**
 * Runs the stack in a thread context
 * @param scope Object filled with runnables, generated by the ScopeBuilder
 */
void ScopeThreadRunner_runStack(ScopeObject scope);

#endif
