/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev */

#include "Scope/Serialisation/Protobuf/se-scope.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(PB_SC_Trigger, PB_SC_Trigger, AUTO)


PB_BIND(PB_SC_Channel, PB_SC_Channel, AUTO)


PB_BIND(PB_SC_Data, PB_SC_Data, AUTO)


PB_BIND(PB_SC_Channel_Configuration, PB_SC_Channel_Configuration, AUTO)


PB_BIND(PB_Announce, PB_Announce, AUTO)


PB_BIND(PB_AddressConfig, PB_AddressConfig, AUTO)


PB_BIND(PB_CF_Address, PB_CF_Address, AUTO)


PB_BIND(PB_RunningConfig, PB_RunningConfig, AUTO)


PB_BIND(PB_CF_Running, PB_CF_Running, AUTO)


PB_BIND(PB_CF_Trigger, PB_CF_Trigger, AUTO)


PB_BIND(PB_CF_TInc, PB_CF_TInc, AUTO)


PB_BIND(PB_EV_Poll, PB_EV_Poll, AUTO)





