/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev */

#include "Scope/Serialisation/Protobuf/se-scope.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SC_Trigger, SC_Trigger, AUTO)


PB_BIND(SC_Channel, SC_Channel, AUTO)


PB_BIND(SC_Data, SC_Data, AUTO)





